### ISSUE TITLE
Add avatar icons to server bots run by @michael

### ISSUE THREAD

**Issue by mikehikes** [theatl-social/theatl-social-content#3]
Other than the Urbanize and Beltline news bots, there are no avatar icons for the respective bots operated by @michael. To provide a better visual identity to the other bots, avatars should be set for those bots.

**Comment by b-bayport** [comment]
Consider these images pilfered from a web image search
![image](https://user-images.githubusercontent.com/121366909/209481559-014c6447-4d3c-4b3e-89d1-64820fd6880a.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481561-41f0dc9c-8188-4749-b916-4a3ec33d7e55.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481564-d54c6fed-3123-4580-850c-e9d353e5d292.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481573-589eb527-6cc9-4091-9a2d-a9896fa93696.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481576-18ebddc3-0d1a-4ec4-a28a-e818fea24788.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481579-d732c899-ecbb-497b-b095-de534cb9f8cf.jpeg)

**Comment by b-bayport** [comment]
![image](https://user-images.githubusercontent.com/121366909/209481587-69120fbb-63a9-4a29-b3b1-560440b28548.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481590-be74bba1-f566-49c9-96a6-b9fc91214a2a.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481591-8298eb57-3cea-4537-a95f-3e1a7f085e16.jpeg)
![image](https://user-images.githubusercontent.com/121366909/209481594-4ce2efa5-6abc-4dbf-a74f-99f1df9add80.jpeg)

**Comment by b-bayport** [comment]
For the sportsbots, you can use these emoji

- [ ] ![hawks](https://user-images.githubusercontent.com/121366909/209701273-7291400a-7501-41ad-aa6d-fec1ae17efa9.png)
- [ ] ![atlanta_dream_wnba](https://user-images.githubusercontent.com/121366909/209701283-7c485ae5-3b07-4da0-beb0-25365d125be0.png)
- [ ] ![atlanta_united](https://user-images.githubusercontent.com/121366909/209701288-4380c1f7-69a0-42b4-a6f5-19018e0a9fcf.png)
- [ ] ![falcons](https://user-images.githubusercontent.com/121366909/209701293-7b605da0-7c9e-451f-8eb4-f7bcd810a829.jpg)
- [ ] ![braves](https://emojis.slackmojis.com/emojis/images/1643514233/2006/braves.png)

**Comment by mikehikes** [comment]
@b-bayport Sports accounts avatars updated!

**Comment by mikehikes** [comment]
All of the avatar icons for which a copyright permitted upload have been updated. Although I still need to figure out what to do with the arts and decatur accounts.
