### ISSUE TITLE
Trending Hashtags & News

### ISSUE THREAD

**Issue by b-bayport** [theatl-social/theatl-social-content#6]
Trending hashtags coming up blank for me on both the iOS Mastodon app and mobile web browser Safari on iOS.  
Is this something that needs to be turned on or just caused by the instance still being small?
Let me know if need screenshots or any other details.

Also the "News" tab feature on iOS app is blank. I checked the documentation and I suspect the "News" items are "Trending Links"

Reference:
https://docs.joinmastodon.org/methods/trends/

**Comment by mikehikes** [comment]
I will double-check settings to confirm. I am using the Toot app on iOS, but I'll load the Mastodon app and test against the server settings.

**Comment by b-bayport** [comment]
It is working now. I checked both the iOS app and mobile browser page.  
I am seeing both hashtags and posts and news tabs populated. 

I think ok to close this issue. 
Thanks!
