### ISSUE TITLE
Markdown formatting?

### ISSUE THREAD

**Issue by b-bayport** [theatl-social/theatl-social-content#7]
Is it possible to add markdown formatting to an instance?  

I would love to be able to do _itallics_, **bold**, and 
> block quotes

**Comment by mikehikes** [comment]
I'll check this out. I'm not sure if this is in the main version of Mastodon, but is on the test ("glitch") versions. This functionality may be coming soon in the next minor version release.

**Comment by mikehikes** [comment]
Under consideration in Mastodon main branch: https://github.com/mastodon/mastodon/issues/18958
