### ISSUE TITLE
Scale back the newsbots

### ISSUE THREAD

**Issue by b-bayport** [theatl-social/theatl-social-content#8]
Can we (you) scale back the frequency of posting by the various newsbots?

Searching the #Atlanta hashtag yields too high of a bot:human post ratio. The human posts are being swamped by the bot posts

**Comment by mikehikes** [comment]
@b-bayport  Currently, the posts are set to every hour. I will change to every 3 hours for now. I think it would be helpful to also review news sources - or, perhaps to break out news sources into separate accounts instead of one single account? let me know what you think!

**Comment by b-bayport** [comment]
I saw the split into separate accts while in parallel I created yet another newsbot for Cobb county... and it's got me thinking 'I don't know maybe we have too many newsbots?'
But I don't know how to down select... like based on what criteria?

It would be good to get input from other members here on the server about this

**Comment by mikehikes** [comment]
@b-bayport - I'll be sending out an updated newsletter today and/or tomorrow, but was going to host a Google Meet call for server supporters (Patreon patrons) this week to discuss. (and future calls scheduled for supporters going forward). Likewise, I think input from other members would be helpful for figuring this out.

**Comment by b-bayport** [comment]
@mikehikes feel free to close this issue at your discretion. I'm good from  my perspective

**Comment by mikehikes** [comment]
Closing issue
