### ISSUE TITLE
custom emoji for the server

### ISSUE THREAD

**Issue by b-bayport** [theatl-social/theatl-social-content#9]
Consider adding these custom emoji to theATL.social server

- [ ] ![1e10](https://user-images.githubusercontent.com/121366909/209698793-4ce22c4b-393d-404c-ab52-902fc8c9a718.png)
- [ ] ![100](https://user-images.githubusercontent.com/121366909/209698795-41160618-1645-43d1-80e2-728eeddcca8c.gif)
- [ ] ![100_rainbow](https://user-images.githubusercontent.com/121366909/209698797-ebd275a9-d040-473f-85af-2630654f8df9.gif)
- [ ] ![300](https://user-images.githubusercontent.com/121366909/209698799-3b69cec9-b4ea-4d06-ab79-00e16e49876a.png)
- [ ] ![1000000](https://user-images.githubusercontent.com/121366909/209698800-6ce7324b-90da-481b-ab68-da463960acf9.png)
- [ ] ![atlanta_dream_wnba](https://user-images.githubusercontent.com/121366909/209698802-36614f41-607a-41d5-9972-23bdddb174a2.png)
- [ ] ![atlanta_united](https://user-images.githubusercontent.com/121366909/209698803-9ad6f0cc-0bfc-4b42-9d07-d3d6fe5f1e88.png)
- [ ] ![braves](https://emojis.slackmojis.com/emojis/images/1643514233/2006/braves.png)
- [ ] ![falcons](https://user-images.githubusercontent.com/121366909/209698806-c13ffe11-47d4-4400-aac3-a69f7fdb15be.jpg)
- [ ] ![fire](https://user-images.githubusercontent.com/121366909/209698808-a8df47ce-b2d9-48ab-852c-07d86283e086.gif)
- [ ] ![hawks](https://user-images.githubusercontent.com/121366909/209698809-9f98269a-c7c2-41de-9302-c97ae85332dc.png)
- [ ] ![mario_levelup](https://user-images.githubusercontent.com/121366909/209698810-35a9f722-5544-4d49-8d46-2bb31685df47.png)
- [ ] ![mario_luigi_dance](https://user-images.githubusercontent.com/121366909/209698811-1dcfce48-aa12-4da9-b177-9b99cc8809dd.gif)
- [ ] ![mario_mushroom](https://user-images.githubusercontent.com/121366909/209698812-ffc97e80-26fa-4002-8893-e6b52414bdd5.jpg)
- [ ] ![mind_blown](https://user-images.githubusercontent.com/121366909/209698813-40dc38a1-711a-473a-a13a-b856ca5be1a3.gif)
- [ ] ![mood](https://user-images.githubusercontent.com/121366909/209698816-269c25b3-3e1b-44a2-9685-4a0b03611980.png)
- [ ] ![no](https://user-images.githubusercontent.com/121366909/209698818-72b5cf97-87aa-4195-8007-884d83fa6e47.gif)
- [ ] ![nod](https://user-images.githubusercontent.com/121366909/209698820-a7052a43-c4da-4d07-88fc-bd88823cf33d.gif)
- [ ] ![peanut_butter_jelly_time](https://user-images.githubusercontent.com/121366909/209698822-2ea0465c-9e1f-4afb-a76b-51e5d625891b.gif)
- [ ] ![picard-facepalm](https://user-images.githubusercontent.com/121366909/209698823-c90705cd-1b5c-4bac-91f6-3ca0ab204fe7.gif)
- [ ] ![picard-why](https://user-images.githubusercontent.com/121366909/209698825-a1599ac1-2d9b-4244-b854-b4e2fb28ba85.png)
- [ ] ![redford_nod](https://user-images.githubusercontent.com/121366909/209698826-b2040cc6-1396-4245-aa10-0ee577c29199.gif)
- [ ] ![snoopy_guitar](https://user-images.githubusercontent.com/121366909/209698827-d40ec868-a83a-4fd7-a578-6f09b2714782.gif)
- [ ] ![snoopy_roof](https://user-images.githubusercontent.com/121366909/209698828-9ee76c69-430e-4047-8c10-92cd6964fd05.gif)
- [ ] ![this-is-fine-fire](https://user-images.githubusercontent.com/121366909/209698830-8ea94048-362f-474a-b2e3-bde80eebec7a.gif)
- [ ] ![what](https://user-images.githubusercontent.com/121366909/209698832-174cd964-8942-46ea-a164-76c1605f522f.jpg)
- [ ] ![wizard](https://user-images.githubusercontent.com/121366909/209698833-b4cebd38-403d-4759-8996-a716808fdec4.gif)
- [ ] ![yes](https://user-images.githubusercontent.com/121366909/209698835-d25fbd9a-05d8-4988-8460-bc289dd9b630.gif)
- [ ] ![youwhat](https://user-images.githubusercontent.com/121366909/209698787-7444435b-90fb-40ce-886b-728eb8028eb8.gif)

**Comment by mikehikes** [comment]
@b-bayport  Awesome! Yes, I'd love to add those. I'll have an opportunity on Monday - also, I'd like to put together a group of people interested in admin/moderating work (for adding emojis, etc.) I'll catch up with you next week!

**Comment by mikehikes** [comment]
@b-bayport - done! There were a few that were jpegs and couldn't be uploaded, but most should be on there now.
